#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
kpack_version: dev
controller:
  image: controller
webhook:
  image: webhook
build_init:
  image: build-init
build_waiter:
  image: build-waiter
build_init_windows:
  image: build-init-windows
rebase:
  image: rebase
completion:
  image: completion
completion_windows:
  image: completion-windows
lifecycle:
  image: lifecycle
